cinema_admin:
    resource: "@cinemaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

cinemafilm:
    resource: "@cinemafilmBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
